### ISSUE TITLE
Project seams "dead"

### ISSUE THREAD

**Issue by Neppord** [csicar/pskt#8]
Hi, I would love to start using pskt but there seams to be dead:
 * no commits for a while
 * the ci tag is red
 * latest release is not latest commit 
 * link in the readme is dead
 
 How can I easily verify that I can run pskt in my Kotlin project, on mac/linux/windows?
 
 If at least I can verify the last ci run being green i would not feel that this project is "dead".

**Comment by csicar** [comment]
I see how the project may seem dead. But in fact, it's not :)
The current state is:
- Building on linux should work just fine. (It's a simple `stack` project)
- I have not tested building on mac/windows in some time, but I see no reason why it should not work
- pskt is not yet updated for purescript 0.14 (There are probably a few minor changes necessary to get it working. If I find time, I'll implement them)
- FFI-Files were created for a lot of standard purescript libraries
- no ui library for android

CI runs just fine for ubuntu 20.04; only 18.04 failed (see here: https://gitlab.com/csicar/pskt/-/pipelines/197303864)
I don't quite know why the links are dead. Maybe sth in GitLab CI changed?
