### ISSUE TITLE
References to purescript-native

### ISSUE THREAD

**Issue by nwolverson** [csicar/pskt#9]
There are some references to `purescript-native`, in particular package.yaml points to the wrong place in the metadata:

```
github:              "andyarvanitis/purescript-native"
license:             BSD3
author:              "Andy Arvanitis"
```

Probably need to update `LICENSE`, less importantly changelog. Of course there should be reference to the fact this is based on `purescript-native`, appropriate credit etc, just some of those files suggest that it *is* that.

**Comment by csicar** [comment]
Oh yeah. I haven't updated any of the metadata yet.  I should probably change the github link and author.
I also haven't started changing the changelog yet.
The License is intentionally left the same to avoid any License-Conflicts.
I think the readme already refers to the fact, that pskt is forked from purescript-native. Should I also reference `purescript-native` somewhere else?

If you notice any other problems feel free to open issues or prs :)
